# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        # Make this depend on your FIRST custom cars migration
        ('cars', '0002_auto_20150603_0642'),
    ]

    # Convert "operations" to only be "state_operations"
    state_operations = [
        # Theses migrations were auto-generated by Django makemigrations.
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=40, verbose_name=b'Brand Name')),
                ('size', models.FloatField(default=17.0, verbose_name=b'Tire R')),
            ],
            options={
                'verbose_name_plural': 'Tires',
            },
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed a
        # "cars_tires" table to "tires_tires" earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]